# This workflow installs dependencies, runs tests, and checks code quality
# without deploying to any platform.

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Node.js environment
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Lint the code
    - name: Lint Code
      run: npm run lint

    # Run tests
    - name: Run Tests
      run: npm test

    # Optionally build the project (if you have a build process)
    - name: Build Project
      run: npm run build --if-present